--------------------------------------------------------
--  DDL for Table BANKS_MASTER
--------------------------------------------------------

create table "BANKS_MASTER" (
   "BANK_NAME"     varchar2(40),
   "BRANCH_NAME"   varchar2(100),
   "BANK_CITY"     varchar2(50) default 'BENGALURU',
   "BANK_PIN_CODE" number,
   "BANK_ABBR"     varchar2(20),
   "BANK_ADDRESS"  varchar2(500),
   "BANK_ID"       number
      generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache
      20 noorder nocycle nokeep noscale,
   "CREATED_AT"    date default sysdate
);