--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

create table "CUSTOMERS" (
   "CUST_ID"        number
      generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 64 cache 20
      noorder nocycle nokeep noscale,
   "USER_NAME"      varchar2(1000 char),
   "PASSWORD"       varchar2(1000 char),
   "FIRST_NAME"     varchar2(1000 char),
   "LAST_NAME"      varchar2(1000 char),
   "DOB"            varchar2(20),
   "GENDER"         varchar2(10 char),
   "PHONE_NBR"      number,
   "EMAIL"          varchar2(1000 char),
   "CUST_PIN_CODE"  number,
   "CUST_CITY"      varchar2(100 char),
   "CUST_ADDRESS"   varchar2(2000 char),
   "CREATED_AT"     date default sysdate,
   "PREFERRED_NAME" varchar2(20),
   "IS_ADMIN"       varchar2(1) default 'N',
   "LAST_LOGGED_IN" date
);