--------------------------------------------------------
--  DDL for Table INSTRUMENT_TYPES
--------------------------------------------------------

create table "INSTRUMENT_TYPES" (
   "INSTRUMENT_TYPE_ID"   number
      generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 62 cache 20
      noorder nocycle nokeep noscale,
   "INSTRUMENT_TYPE_CD"   varchar2(10),
   "INSTRUMENT_TYPE_DESC" varchar2(100),
   "CREATED_AT"           date default sysdate
);

comment on table "INSTRUMENT_TYPES" is
   'Contains the types of instrument types';