--------------------------------------------------------
--  DDL for Table INVESTMENT_DETAILS
--------------------------------------------------------

create table "INVESTMENT_DETAILS" (
   "INVESTMENT_ID"         number
      generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 184 cache 20
      noorder nocycle nokeep noscale,
   "ACCOUNT_NBR"           varchar2(100),
   "INSTRUMENT_TYPE"       varchar2(10),
   "INSTRUMENT_ID"         varchar2(100),
   "INSTRUMENT_NAME"       varchar2(100),
   "INSTRUMENT_ASSOC_BANK" varchar2(100),
   "INVESTMENT_AMT"        number,
   "INVESTMENT_DT"         date,
   "INSTRUMENT_CLOSED_DT"  date,
   "ACTIVE_FLAG"           varchar2(1 char) default 'Y',
   "INVESTMENT_TYPE"       varchar2(10) default 'SIP',
   "CREATED_AT"            date default sysdate,
   "EXPIRATION_DT"         date
);

comment on table "INVESTMENT_DETAILS" is
   'Stores the investment details for an account (combination of user, bank and branch.)';