--------------------------------------------------------
--  DDL for Table INVESTMENT_TYPES
--------------------------------------------------------

create table "INVESTMENT_TYPES" (
   "INVESTMENT_TYPE_ID"   number
      generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 62 cache 20
      noorder nocycle nokeep noscale,
   "INVESTMENT_TYPE_CD"   varchar2(10),
   "INVESTMENT_TYPE_DESC" varchar2(100),
   "CREATED_AT"           date default sysdate
);